---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: fedifetcher-pvc
spec:
  accessModes:
    - ReadWriteOnce
  volumeMode: Filesystem
  resources:
    requests:
      storage: 100Mi
---
apiVersion: batch/v1
kind: CronJob
metadata:
  name: FediFetcher
spec:
  # Run every 2 hours
  schedule: "0 */2 * * *"
  successfulJobsHistoryLimit: 1
  failedJobsHistoryLimit: 1
  concurrencyPolicy: Forbid
  jobTemplate:
    spec:
      template:
        spec:
          volumes:
            - name: artifacts
              persistentVolumeClaim:
                claimName: fedifetcher-pvc
          containers:
            - name: FediFetcher
              image: ghcr.io/nanos/fedifetcher:latest
              args:
                - --server=your.server.social
                - --access-token=TOKEN
                - --home-timeline-length
                - "200"
                - --reply-interval-in-hours
                - "24"
                - --max-followings
                - "80"
                - --max-followers
                - "80"
              volumeMounts:
                - name: artifacts
                  mountPath: /app/artifacts
          restartPolicy: Never
